### ISSUE TITLE
Potential Error in documentation @rpldy/chunked-uploady

### ISSUE THREAD

**Issue by vakharia-aarya** [rpldy/react-uploady-docs#3]
I was trying to implement a version of chunked upload using chunked-uploady. 

However there seems to be an error in the "example" section of the documentation. 

![image](https://user-images.githubusercontent.com/98556746/231292939-ed81e084-d6c5-4b53-b99f-2614883839d5.png)

In the first line while importing the ChunkedUploady, shouldn't it be: 

`import ChunkedUploady from "@rpldy/chunked-uploady";`

 instead of 

`import ChunkedUploady from "@rpldy/uploady";`

I may be wrong, but while implementing the example code I was not getting the intended behavior (probably because it was using the uploader instead of the chunked uploader) and after debugging and making the change I was able to get it working. Again, not an expert but thought should at least report it lol.

**Comment by yoavniran** [comment]
absolutely @vakharia-aarya , this is a mistake.
Will be fixed shortly. 
Thanks!
